CampingsProject/CampingsProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls), # url por defecto para administrar el sitio
    path('', include('sitio.urls')), # incluye las urls de la app pagina
    path('foro/', include('foro.urls')),
    path('reservas/', include('reservas.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'), #vista de contraseña cambiada correctamente
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CampingsProject/foro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.forumposts, name='forumposts'),
    path('tema/<int:pk>/', views.forumpostdetail, name='forumpostdetail'),
    path('nuevotema/', views.addforumpost, name='addforumpost'),
    path('tema/<int:pk>/delete/', views.deleteforumpost, name='deleteforumpost'),
    path('respuesta/<int:pk>/delete/', views.deleteanswer, name='deleteanswer'),
    path('likeanswer/<int:pk>/', views.likeanswer, name= 'likeanswer'),
]

CampingsProject/star_ratings/urls.py
from __future__ import unicode_literals

from django.urls import re_path

from .views import Rate
from . import app_settings

from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import urls as auth_urls
from .views import FooView, SizesView


urlpatterns = [
    re_path(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
    path('', FooView.as_view(template_name='home_copy.html'), name='home'),
    path('sizes', SizesView.as_view(), name='sizes'),
    #path('', include(auth_urls)),
    #path('admin/', admin.site.urls),
]

app_name = 'star_ratings'

CampingsProject/star_ratings/models.py
from __future__ import division, unicode_literals
from decimal import Decimal

import swapper
from warnings import warn
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models import Avg, Count, Sum
from django.utils.translation import ugettext as _
from model_utils.models import TimeStampedModel

from . import app_settings, get_star_ratings_rating_model_name, get_star_ratings_rating_model


class Foo(models.Model):
    bar = models.CharField(max_length=100)


def _clean_user(user):
    if not app_settings.STAR_RATINGS_ANONYMOUS:
        if not user:
            raise ValueError(_("User is mandatory. Enable 'STAR_RATINGS_ANONYMOUS' for anonymous ratings."))
        return user
    return None


class RatingManager(models.Manager):
    def for_instance(self, instance):
        if isinstance(instance, self.model):
            raise TypeError("Rating manager 'for_instance' expects model to be rated, not Rating model.")
        ct = ContentType.objects.get_for_model(instance)
        ratings, created = self.get_or_create(content_type=ct, object_id=instance.pk)
        return ratings

    def ratings_for_instance(self, instance):
        warn("RatingManager method 'ratings_for_instance' has been renamed to 'for_instance'. Please change uses of 'Rating.objects.ratings_for_instance' to 'Rating.objects.for_instance' in your code.", DeprecationWarning)
        return self.for_instance(instance)

    def delete_existing(self, existing_rating):
        rating = existing_rating.rating
        existing_rating.delete()
        rating._user_rating_deleted = True
        return rating

    def rate(self, instance, score, user=None, ip=None, clear=False):
        if isinstance(instance, self.model):
            raise TypeError("Rating manager 'rate' expects model to be rated, not Rating model.")
        ct = ContentType.objects.get_for_model(instance)

        user = _clean_user(user)
        existing_rating = UserRating.objects.for_instance_by_user(instance, user)

        if existing_rating:
            if not app_settings.STAR_RATINGS_CLEARABLE and not app_settings.STAR_RATINGS_RERATE:
                raise ValidationError(_('Already rated.'))

            same_as_previous = existing_rating.score == score

            if (app_settings.STAR_RATINGS_CLEARABLE and clear) or \
                    (app_settings.STAR_RATINGS_RERATE_SAME_DELETE and same_as_previous):
                return self.delete_existing(existing_rating=existing_rating)
            elif score is not None:
                existing_rating.score = score
                existing_rating.save()
                return existing_rating.rating
        elif clear:
            # user has cleared without an existing_rating
            return
        else:
            rating, created = self.get_or_create(content_type=ct, object_id=instance.pk)
            return UserRating.objects.create(user=user, score=score, rating=rating, ip=ip).rating


class AbstractBaseRating(models.Model):
    """
    Attaches Rating models and running counts to the model being rated via a generic relation.
    """
    count = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)
    average = models.DecimalField(max_digits=6, decimal_places=3, default=Decimal(0.0))

    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey()

    objects = RatingManager()

    class Meta:
        unique_together = ['content_type', 'object_id']
        abstract = True

    @property
    def percentage(self):
        return (self.average / app_settings.STAR_RATINGS_RANGE) * 100

    def to_dict(self):
        return {
            'count': self.count,
            'total': self.total,
            'average': self.average,
            'percentage': self.percentage,
        }

    def __str__(self):
        return '{}'.format(self.content_object)

    def calculate(self):
        """
        Recalculate the totals, and save.
        """
        aggregates = self.user_ratings.aggregate(total=Sum('score'), average=Avg('score'), count=Count('score'))
        self.count = aggregates.get('count') or 0
        self.total = aggregates.get('total') or 0
        self.average = aggregates.get('average') or 0.0
        self.save()


class Rating(AbstractBaseRating):
    class Meta(AbstractBaseRating.Meta):
        swappable = swapper.swappable_setting('star_ratings', 'Rating')


class UserRatingManager(models.Manager):
    def for_instance_by_user(self, instance, user=None):
        ct = ContentType.objects.get_for_model(instance)
        user = _clean_user(user)
        if user:
            return self.filter(rating__content_type=ct, rating__object_id=instance.pk, user=user).first()
        else:
            return None

    def has_rated(self, instance, user=None):
        if isinstance(instance, get_star_ratings_rating_model()):
            raise TypeError("UserRating manager 'has_rated' expects model to be rated, not UserRating model.")

        rating = self.for_instance_by_user(instance, user=user)
        return rating is not None

    def bulk_create(self, objs, batch_size=None):
        objs = super(UserRatingManager, self).bulk_create(objs, batch_size=batch_size)
        for rating in set(o.rating for o in objs):
            rating.calculate()
        return objs


class UserRating(TimeStampedModel):
    """
    An individual rating of a user against a model.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    ip = models.GenericIPAddressField(blank=True, null=True)
    score = models.PositiveSmallIntegerField()
    rating = models.ForeignKey(get_star_ratings_rating_model_name(), related_name='user_ratings', on_delete=models.CASCADE)

    objects = UserRatingManager()

    class Meta:
        unique_together = ['user', 'rating']

    def __str__(self):
        if not app_settings.STAR_RATINGS_ANONYMOUS:
            return '{} rating {} for {}'.format(self.user, self.score, self.rating.content_object)
        return '{} rating {} for {}'.format(self.ip, self.score, self.rating.content_object)

CampingsProject/star_ratings/forms.py
from __future__ import absolute_import
from django import forms

from . import get_star_ratings_rating_model, app_settings
from .models import UserRating


class CreateUserRatingForm(forms.ModelForm):
    clear = forms.BooleanField(required=False)

    class Meta:
        model = UserRating
        exclude = [
            'count',
            'total',
            'average',
            'rating',
        ]

    def __init__(self, obj=None, *args, **kwargs):
        self.obj = obj
        super(CreateUserRatingForm, self).__init__(*args, **kwargs)

        if self.data.get('clear', False) and app_settings.STAR_RATINGS_CLEARABLE:
            self.fields['score'].required = False

    def save(self, commit=True):
        return get_star_ratings_rating_model().objects.rate(
            self.obj,
            self.cleaned_data['score'],
            user=self.cleaned_data['user'],
            ip=self.cleaned_data['ip'],
            clear=self.cleaned_data['clear'],
        )

CampingsProject/star_ratings/views.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import View

from . import app_settings, get_star_ratings_rating_model
from .forms import CreateUserRatingForm
from .compat import is_authenticated
import json

from django.views.generic import DetailView, TemplateView
from .models import Foo


class FooView(DetailView):
    model = Foo

    def get_object(self, queryset=None):
        obj, created = Foo.objects.get_or_create(bar='foo bar baz')
        return obj


class SizesView(TemplateView):
    model = Foo
    template_name = 'sizes.html'

    def get_context_data(self, **kwargs):
        kwargs['sizes'] = {size: self.model.objects.get_or_create(bar=str(size))[0] for size in range(10, 40)}
        return super(SizesView, self).get_context_data(**kwargs)



class Rate(View):
    model = get_star_ratings_rating_model()

    def get_object(self):
        """
        Returns the model instance we're rating from the URL params.
        """
        content_type = ContentType.objects.get_for_id(self.kwargs.get('content_type_id'))
        return content_type.get_object_for_this_type(pk=self.kwargs.get('object_id'))

    def post(self, request, *args, **kwargs):
        def _post(request, *args, **kwargs):
            data = request.POST or json.loads(request.body.decode())

            return_url = data.pop('next', '/')
            if 'HTTP_X_REAL_IP' in self.request.META:
                data['ip'] = self.request.META['HTTP_X_REAL_IP']
            else:
                data['ip'] = self.request.META['REMOTE_ADDR']

            data['user'] = is_authenticated(request.user) and request.user.pk or None

            res_status = 200
            result = {}

            try:
                form = CreateUserRatingForm(data=data, obj=self.get_object())
                if form.is_valid():
                    rating = form.save()
                    if rating:
                        result = rating.to_dict()

                        user_rating = form.cleaned_data.get('score')
                        if hasattr(rating, '_user_rating_deleted'):
                            user_rating = None

                        if user_rating:
                            user_rating = int(user_rating)

                        result['user_rating'] = user_rating
                else:
                    result = {'errors': form.errors}
                    res_status = 400
            except ValidationError as err:
                result = {'errors': err.message}
                res_status = 400

            if request.is_ajax():
                return JsonResponse(data=result, status=res_status)
            else:
                return HttpResponseRedirect(return_url)

        if not app_settings.STAR_RATINGS_ANONYMOUS:
            return login_required(_post)(request, *args, **kwargs)

        return _post(request, *args, **kwargs)

CampingsProject/star_ratings/templates/star_ratings/widget.html
{% extends "star_ratings/widget_base.html" %}

CampingsProject/star_ratings/templates/star_ratings/widget_base.html
{% load i18n %}
{% block rating_style %}
<style>
    #{{ id }} .star-ratings-rating-full, #{{ id }} .star-ratings-rating-empty {
        width: {{ icon_width }}px;
        height: {{ icon_height }}px;
        background: url({{ sprite_image }}) no-repeat;
        background-size: {{ sprite_width }}px;
    }

    #{{ id }} .star-ratings-rating-empty {
        background-position: -{{ icon_width }}px 0;
    }

    {% if user.is_authenticated and editable %}
    #{{ id }} .star-ratings-rating-full:hover, #{{ id }} .star-ratings-rating-empty:hover {
        background-position: -{{ icon_width|add:icon_width }}px 0;
    }
    {% endif %}
</style>
{% endblock rating_style %}

{% block rating_container %}
<div id="{{ id }}" class="star-ratings" data-max-rating="{{ star_count }}" data-avg-rating="{{ rating.average }}">
    {% block rating_stars %}
        <div class="star-ratings-rating-stars-container">
            <ul class="star-ratings-rating-background">
                {% for star in stars %}
                    <li>
                        {% if editable %}
                        <form action="{% url 'ratings:rate' rating.content_type_id rating.object_id %}" class="star-ratings-rate-action" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{ star }}" name="score">
                            <input type="hidden" value="{{ request.path }}" name="next">
                            <button type="submit" class="star-ratings-rating-empty" data-score="{{ star }}"></button>
                        </form>
                        {% elif user.is_authenticated %}
                            <span class="star-ratings-rating-empty"></span>
                        {% else %}
                            <span class="star-ratings-rating-empty" title="{% trans 'Inicia sesion para calificar' as title_login %}{{ title_login|escape }}"></span>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>

            <ul class="star-ratings-rating-foreground" style="width: {{ percentage|floatformat }}%">
                {% for star in stars %}
                    <li>
                    {% if editable %}
                    <form action="{% url 'ratings:rate' rating.content_type_id rating.object_id %}" class="star-ratings-rate-action" method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ star }}" name="score">
                        <input type="hidden" value="{{ request.path }}" name="next">
                        <button type="submit" class="star-ratings-rating-full" data-score="{{ star }}"></button>
                    </form>
                    {% else %}
                        <span class="star-ratings-rating-full" title="Log in to rate"></span>
                    {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endblock %}
    {% block rating_detail %}
    {% block rating_average %}
    {# <div class="star-ratings-rating-average">{% trans 'Promedio ' %} <span class='star-ratings-rating-value'>{{ rating.average|floatformat:"-2" }}</span></div> #}
    {% endblock rating_average %}
    {% block rating_count %}
    {# <div class="star-ratings-rating-count">{% trans 'Reviews ' %} <span class='star-ratings-rating-value'>{{ rating.count }}</span></div> #}
    {% endblock rating_count %}
    {% block rating_user %}
    {# <div class="star-ratings-rating-user">{% trans 'Tu review ' %} <span class='star-ratings-rating-value' data-when-null="{% trans 'Not rated' %}">{% if user_rating %}{{ user_rating.score }}{% else %}{% trans 'Not rated' %}{% endif %}</span></div> #}
    
    {% endblock rating_user %}
    <div class="star-ratings-errors"></div>
    {% block rating_clearable %}
        {% if clearable %}
            <div class="star-ratings-clear star-ratings-clear-{{user_rating|yesno:'visible,hidden'}}">
                <form action="{% url 'ratings:rate' rating.content_type_id rating.object_id %}" class="star-ratings-rate-action" method="post">
                {% csrf_token %}
                <input type="hidden" value="1" name="clear">
                <input type="hidden" value="{{ request.path }}" name="next">
                <button type="submit" class="star-ratings-rating-clear">Clear</button>
                </form>
            </div>
        {% endif %}
    {% endblock %}
    {% endblock rating_detail %}
</div>
{% endblock rating_container %}