CampingsProject/CampingsProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls), # url por defecto para administrar el sitio
    path('', include('sitio.urls')), # incluye las urls de la app pagina
    path('foro/', include('foro.urls')),
    path('reservas/', include('reservas.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'), #vista de contraseña cambiada correctamente
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CampingsProject/foro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.forumposts, name='forumposts'),
    path('tema/<int:pk>/', views.forumpostdetail, name='forumpostdetail'),
    path('nuevotema/', views.addforumpost, name='addforumpost'),
    path('tema/<int:pk>/delete/', views.deleteforumpost, name='deleteforumpost'),
    path('respuesta/<int:pk>/delete/', views.deleteanswer, name='deleteanswer'),
    path('likeanswer/<int:pk>/', views.likeanswer, name= 'likeanswer'),
]

CampingsProject/sitio/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (home,
                    iniciar_sesion,
                    registrarse,
                    cerrar_sesion,
                    reservaciones,
                    detalle_camping,
                    campings,
                    listar,
                    agregar_editar,
                    eliminar_banner,
                    activate,
                    borrarcamping,
                    abmcamping,
                    eliminar_comentario,
                    autocomplete,
                    denuncias,
                    descartardenuncias,
                    autocompleteForumpost
                    )

from django.contrib.auth import views as auth_views
from django.conf.urls import url
from foro.views import forumpostdetail, deleteforumpost
from reservas.views import mis_reservas
from foro import views

app_name = 'sitio'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', iniciar_sesion, name='iniciosesion'),
    path('registrarse/', registrarse, name='registrarse'),
    path('cerrarsesion/', cerrar_sesion, name='cerrarsesion'),

    path('reservaciones/', reservaciones, name='reservaciones'),
    path('campings/<int:pk>/', campings, name = 'campings'),
    # path('campings/', campings, name='campings'),
    path('detallecamping/<int:pk>/', detalle_camping, name='detalle_camping'),
    path('banners/', listar, name='lista_banners'),
    path('banner/', agregar_editar, name='banner'),
    path('banner/<int:pk>/', agregar_editar, name='banner_detalle'),
    path('banner/<int:pk>/delete/', eliminar_banner, name='eliminar'),
    # path('nuevocamping/', nuevocamping, name='nuevocamping'),
    path('abmcamping/', abmcamping, name='abmcamping'),
    #path('modificarcamping/<int:pk>/', modificarcamping, name='modificarcamping'),
    path('borrarcamping/<int:pk>/', borrarcamping, name='borrarcamping'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    #comentarios
    path('comentario/<int:pk>/delete/', eliminar_comentario),
    path('reservas/', include('reservas.urls')),

    path('misreservas/', mis_reservas, name='misreservas'),

    path('search/', include('haystack.urls')),
    path('foro/search/', include('haystack.urls')),

    path('forumpostdetail/<int:pk>/', forumpostdetail, name='forumpostdetail'),
    path('deleteforumpost/<int:pk>/', deleteforumpost, name='deleteforumpost'),

    url(r'^search/autocomplete',autocomplete, name='autocomplete'),
    url(r'^foro/search/autocomplete',autocompleteForumpost, name='autocomplete'),

    path('denuncias/', denuncias, name='denuncias'),

    path('descartardenuncias/<int:pk>/', descartardenuncias, name= 'descartardenuncias'),

    path('denuncia/<int:pk>/', views.denuncia, name= 'denuncia'),
]

CampingsProject/foro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

from sitio.models import Motivo

class ForumPost(models.Model):
    title = models.CharField(max_length=30)
    body = RichTextField(blank=True, null=True)
    #body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ' | ' + str(self.author)


class Comentario(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name='responde')
    post = models.ForeignKey(ForumPost, on_delete=models.CASCADE, related_name='comentarios') # el related_name nos va a permitir acceder a los comentarios desde los campings
    contenido = models.CharField(max_length=500)
    #temaForo = models.ForeignKey(TemaForo, on_delete=models.CASCADE, blank=True, default='')
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    liked = models.BooleanField(default=False)
    likes = models.ManyToManyField(User, related_name='forum_answers')
    denuncias = models.ManyToManyField(User, related_name='denuncia')

    def __str__(self):
        return self.contenido

    def total_likes(self):
        return self.likes.count()

    def total_denuncias(self):
        return self.denuncias.count()


CHOICES= (
('1','Contenido discriminativo'),
('2','Comentario violento'),
('3','Comentario de amenaza'),
('4','Contenido irrespetuoso'),
('5','Otro'),
)

class Denuncias(models.Model):
    comentario = models.ForeignKey(Comentario, on_delete=models.CASCADE, related_name='comentario_denunciado')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuario_que_denuncia')
    select = models.ForeignKey(Motivo, on_delete=models.CASCADE)

CampingsProject/foro/forms.py
from django import forms
from .models import ForumPost, Comentario, CHOICES, Denuncias

class ForumPostForm(forms.ModelForm):
    class Meta:
        model = ForumPost
        fields = ('title', 'body',)

class ComentariosForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido',]
        widgets = {
            'contenido': forms.TextInput(attrs={'placeholder': 'Contenido'}),
        }


class DenunciaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DenunciaForm, self).__init__(*args,**kwargs)
    
    class Meta:
        model = Denuncias
        fields = ['select',]

CampingsProject/foro/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import ForumPost, Comentario, Denuncias, CHOICES
from .forms import (ForumPostForm,
                    ComentariosForm,
                    DenunciaForm,
                    )
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.db.models import Count
from django.http import JsonResponse

from sitio.models import Motivo

def forumposts(request):
    posts = ForumPost.objects.all()
    return render(request, 'forumposts.html', {'posts':posts})

@login_required
def forumpostdetail(request, pk):
    post = ForumPost.objects.get(pk = pk)
    comentarios = Comentario.objects.filter(post = post).annotate(like_count=Count('likes')).order_by('-like_count')
    #ordenar las respuestas por cantidad de likes
    #Article.objects.annotate(like_count=Count('likes')).order_by('-like_count')
    #COMENTARIOS o sea RESPUESTAS
    if request.method == "POST":
        form = ComentariosForm(data=request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.post = post
            comentario.author = request.user
            comentario.save()
    else:
        form = ComentariosForm()

    # ver si el usuario le puso o no like a la respuesta
    for c in comentarios:
        c.total = c.likes.count()
        if c.likes.filter(id=request.user.id).exists():
            c.liked = True

    #motivos_denuncia = DenunciaForm()
    motivos_denuncia = CHOICES
    denuncias_usuario = Denuncias.objects.filter(user=request.user)
    
    comentarios_denunciados = []
    for denuncia in denuncias_usuario:
        coment = denuncia.comentario
        comentarios_denunciados.append(coment)
    return render(
        request,
        'detail.html',
        {
            'post':post,
            'comentarios': comentarios,
            'motivos': motivos_denuncia,
            'denuncias': comentarios_denunciados,
        }
    )

@login_required
def deleteanswer(request, pk):
    answer = Comentario.objects.get(pk=pk)
    answer.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def addforumpost(request):
    if request.method == "POST":
        form = ForumPostForm(request.POST)
        if form.is_valid():
            forumpost = form.save(commit=False)
            forumpost.author = request.user
            forumpost.save()
            return redirect('forumpostdetail', pk=forumpost.pk)
    else:
        form = ForumPostForm()
    return render(request, 'add_forumpost.html', {'form': form})

@login_required
def deleteforumpost(request, pk):
    # pk del forum post
    forumpost = ForumPost.objects.get(pk = pk)
    forumpost.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def likeanswer(request, pk):
    answer = get_object_or_404(Comentario, id=request.POST.get('answer_id'))
    liked = False
    if answer.likes.filter(id=request.user.id).exists():
        answer.likes.remove(request.user)
        liked = False
    else:
        answer.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('forumpostdetail', args=[str(answer.post.id)]))


def denuncia_anterior(request, pk = None):
    answer = get_object_or_404(Comentario, id=request.POST.get('answer_id'))
    if request.is_ajax():
        form = DenunciaForm(data=request.POST)
        denuncia = Denuncias()
        if form.is_valid:
            
            #if answer.denuncias.filter(id=request.user.id).exists() == False:
            answer.denuncias.add(request.user)
            denuncia.comentario = answer
            denuncia.user = request.user
            #denuncia.select = data['motivo']
            print(denuncia.select)
            #denuncia.save()
            mensaje = "Denuncia correcta"
        else:
            mensaje = "form invalido"
    else:
        mensaje = "NO AJAX"
    return JsonResponse({
		'mensaje': mensaje,
		'url': reverse('forumpostdetail', args=[str(answer.post.id)]),
	})

def denuncia(request, pk):
    answer = get_object_or_404(Comentario, pk=pk)
    if request.method == 'POST': 
        form = DenunciaForm(data=request.POST)
        denuncia = Denuncias()
        if form.is_valid:
            #if answer.denuncias.filter(id=request.user.id).exists() == False:
            answer.denuncias.add(request.user)
            denuncia.comentario = answer
            denuncia.user = request.user
            motivo = Motivo.objects.get(pk=request.POST['select'])
            denuncia.select = motivo
            denuncia.save()
            return HttpResponseRedirect('/')
    else:
        form = DenunciaForm()
    motivos_denuncia = CHOICES
    return render(
        request,
        'denunciar.html',
        {
            'form':form,
            'motivos': motivos_denuncia,
            'comment': answer,
        },
    )

CampingsProject/foro/templates/add_forumpost.html
{% extends "base.html" %}

{% block content %}
<br/>
<h2 class="text-center">Nuevo tema</h2>
<br/>
<div class="container">
    <div class="alert alert-success" role="alert">
        <div style="padding: 30px; width: 100%;" class="text-center">
            <form method="POST">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Guardar</button>
                <a href="{% url 'forumposts' %}"><button type="button" class="btn btn-light" >Cancelar</button></a>
            </form>
        </div>
    </div>
</div>
<br/>
{% endblock content %}

CampingsProject/foro/templates/answers.html
{% load static %}
<style>
    .comment-form {
            width: 100%;
            max-width: 500px;
            padding: 15px;
            margin: auto;
        }
    .btn-primary {
        color: #079748;
        background-color: #fff;
        border-color: #079748;
    }
    .btn-primary:hover {
    color: #fff;
    background-color: #d4bd22;
    border-color: #fff;}
    
    .comment {
            width: 100%;
           
            padding: 15px;
            margin: auto;
    }
</style>
    <h2 class="text-center">Respuestas</h2>
    {% for comment in comentarios %}
        {# {% if user.is_authenticated or comment.approved_comment %} #}
        <div class="container"> 
            <div class="alert alert-warning" role="alert">                     
                <div class="date">
                    <div class="text-right">
                        {% if comment.author == request.user %}
                            <a href="{% url 'deleteanswer' comment.pk %}"class="badge badge-danger"
                                onClick="return confirm('¿Seguro que quieres borrar tu respuesta?');">
                                <strong>Eliminar</strong>
                            </a>
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <p><small>El {{ comment.fechaCreacion }}</small>
                                {% if comment.author == request.user %}
                                <strong>usted</strong> respondió:
                                {% else %}
                                <strong>{{ comment.author }}</strong> respondió:
                                {% endif %}
                            </p>
                        </div>

                        {% if comment.author != user and comment not in denuncias %} 
                        <div class="col-sm-6 text-right">
                            <div class="btn-group">
                                {% comment %}   
                                <button type="button" class="btn btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                Opciones <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                <!-- Button trigger modal -->
                                {% endcomment %}   
                                <a class="badge badge-danger" href="{% url 'sitio:denuncia' comment.pk %}">Denunciar comentario</a>
                                </ul>
                            </div>
                        </div>
                        {% endif %} 
                    </div>
                        
                        <em>{% comment %}</em>
                        {% if not comment.approved_comment %}
                            <a class="btn btn-default" href="{% url 'comment_remove' pk={{comment.pk}} %}"><span class="glyphicon glyphicon-remove"></span></a>
                            <a class="btn btn-default" href="{% url 'comment_approve' pk={{comment.pk}} %}"><span class="glyphicon glyphicon-ok"></span></a>
                        {% endif %}
                        {% endcomment %}
                    
                    <p>{{ comment.contenido|linebreaks }}</p>
                    </p>
                    
                    {% if comment.author == user %}
                        
                    {% else %}
                    <form action="{% url 'likeanswer' comment.pk %}" method="POST">
                        {% csrf_token %}
                        {% if comment.liked %}
                            <button type="submit", name="answer_id", value="{{ comment.id }}"
                            class="btn btn-danger btn-sm">No me gusta</button> 
                        {% else %}
                            <button type="submit", name="answer_id", value="{{ comment.id }}"
                            class="btn btn-success btn-sm">Me gusta</button>
                        {% endif %}
                    </form>
                    {% endif %}
                    {{ comment.total_likes }} me gusta 
                </div>
            </div>
        </div>
    {# {% endif %} #}
    {% empty %}
    <div class="container">
        <div class="comment">
            <strong>Todavía no hay respuestas</strong>
        </div>
    
    </div>
    {% endfor %}
    
    {% if user.is_authenticated %}
        <div id="respond" class="comment-respond; text-center">
            <form action="" method="post" id="commentform" class="comment-form">{% csrf_token %}
                <input class="form-control" required="" placeholder="Tu respuesta" name="contenido">
                <br> 
                <button class="btn btn-lg btn-primary btn-block publicar" type="submit">Responder</button>
            </form>
        </div>
    {% else %}
        <a class="btn btn-default" href="/accounts/login/">Inicia sesión para responder</a>
    {% endif %}




    {% comment %}
    <script src="{% static '/js/Denunciar.js' %}">
        var csrftoken = '{{csrf_token}}';
        $('.denunciar').on('click', onClickDenunciar);
    </script>
    {% endcomment %}

CampingsProject/foro/templates/denunciar.html
{% extends "base.html" %}
<script type="text/javascript" src="lib.js"></script>
{% block content %}
<div class="text-center">
<form action="" method="POST" class="post-form">{% csrf_token %}
    <br>
    <p><strong>Elija un motivo de denuncia</strong></p>
    
    {{ form.select }}
    <br>
    <br>
    <a class="btn btn-secondary" type="button" value="Cancelar" href="{% url 'sitio:forumpostdetail' comment.post.pk %}">Cancelar</a>
    <button class="btn btn-danger btn-denunciar" type="submit" value="Denunciar">Denunciar</button>
    <br>
    <br>
</form>
{% endblock content %}
</div>
<script>

function dimePropiedades(){ 
   	var texto 
   	texto = "El numero de opciones del select: " + document.formul.motivos.length 
   	var indice = document.formul.motivos.selectedIndex 
   	texto += "nIndice de la opcion escogida: " + indice 
   	var valor = document.formul.motivos.options[indice].value 
   	texto += "nValor de la opcion escogida: " + valor 
   	var textoEscogido = document.formul.motivos.options[indice].text 
   	texto += "nTexto de la opcion escogida: " + textoEscogido 
       alert(texto) 
       console.log(texto)
}

</script>



<!-- Modal -->
{% comment %}
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Elija un motivo de denuncia</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endcomment %}
            
            {% comment %}
                {# <button type="button" data-pk-comment="{{ comment.id }}" class="btn btn-danger denunciar">Denunciar</button> #}
        </div>
    </div>
</div>


<script>

    function onDenunciaTerminada(datos){
        print(datos)
        alert(datos);
        window.location.href = 'tema/{{pk}}/';
    }

    function onClickDenunciar(e) {
        NO ANDA NADAAAAAAAAAAAAA
        var target = $(e.target);
        print('target: '+target)
        var pk = target.data("pk-comment");
        // hacer algo con pkCosa, por ejemplo mandar request ajax de denuncia
        var ultimo_motivo = target.data("motivo")
        print('ultimo motivo: '+ultimo_motivo)
        var motivos = document.getElementById("motivos");
        var indiceSeleccionado = motivos.selectedIndex;
        var opcionSeleccionada = motivos.options[indiceSeleccionado];
        var URL ="denuncia/{{pk}}/";
        print('pk de comentario: '+pk)
        print('csrftoken: '+csrftoken)
        var data = {'motivo': opcionSeleccionada, 'pk':pk}; 
        $.post({
            headers: {"X-CSRFToken": csrftoken},   //así django acepta el POST
            url: URL,
            data: data,
        }).done(onDenunciaTerminada);
    }

    $('.btn-denunciar').on('click', onClickDenunciar);
    </script>


{% endcomment %}

CampingsProject/foro/templates/detail.html
{% extends "base.html" %}

{% block content %}
<br/>
<br/>
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">{{ post.title }}</h1>
        <p class="lead">Por <strong>{{ post.author }}</strong></p>
        <hr class="my-4" color="#000000">
        {{ post.body | safe }}
        <a class="btn btn-primary btn-lg" href="{% url 'forumposts' %}" role="button">Volver</a>
    </div>
</div>

{% include "answers.html" %}

{% endblock content %}

CampingsProject/foro/templates/forumposts.html
{% extends "base.html" %}

{% block content %}
<style>
    .btn-primary {
        color: #079748;
        background-color: #fff;
        border-color: #079748;
    }
    .btn-primary:hover {
    color: #fff;
    background-color: #d4bd22;
    border-color: #fff;}
</style>

<br/>
<div class="container">
    <a class="btn btn-primary btn-lg" href="{% url 'addforumpost' %}" role="button">Crear un tema</a>
    <br>
    <br>
    {% include "search_bar_forumpost.html" %}
    <br>
</div>

<br/>
{% for post in posts %}
    <div class="container">
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">
                <a href="{% url 'forumpostdetail' post.pk %}" class="alert-link" onmouseover="this.style.color='#d4bd22'"
                onMouseOut="this.style.color='#000000'"
                >{{ post.title }}</a>
            </h4><small>(click para ver más)</small>
            <hr>
            {% if post.author.username == request.user.username %}
            <p class="mb-0">Publicado por <strong>vos</strong></p>
            <span style="text-align:right;">
                <a href="{% url 'deleteforumpost' post.pk %}" class="badge badge-danger"
                onClick="return confirm('¿Seguro que quieres borrar el tema del foro?');">
                <strong>Eliminar</strong>
            </a>
            </span>
            {% else %}
            <p class="mb-0">Publicado por <strong>{{ post.author }}</strong></p>
            {% endif %}
        </div>
    </div>
<br/>
{% endfor %}
<br/>
{% endblock content %}