CampingsProject/CampingsProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls), # url por defecto para administrar el sitio
    path('', include('sitio.urls')), # incluye las urls de la app pagina
    path('foro/', include('foro.urls')),
    path('reservas/', include('reservas.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'), #vista de contraseña cambiada correctamente
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CampingsProject/foro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.forumposts, name='forumposts'),
    path('tema/<int:pk>/', views.forumpostdetail, name='forumpostdetail'),
    path('nuevotema/', views.addforumpost, name='addforumpost'),
    path('tema/<int:pk>/delete/', views.deleteforumpost, name='deleteforumpost'),
    path('respuesta/<int:pk>/delete/', views.deleteanswer, name='deleteanswer'),
    path('likeanswer/<int:pk>/', views.likeanswer, name= 'likeanswer'),
]

CampingsProject/reservas/urls.py
from .views import reservar, confirmar_reserva, mostrar_confirmar_reserva, rechazar_reserva, mostrar_reservas, reservas_details
from django.urls import path
from django.conf.urls import url

from .views import CalendarView

app_name = 'reservas'
urlpatterns = [
    path('calendar/<int:pk>/reservar/', reservar, name='reservar'),
    path('<int:pk>/reservar/', reservar, name='reservar_dos'),
    path('confirmar/', confirmar_reserva, name='confirmar'),
    path('rechazar/', rechazar_reserva, name='rechazar'),
    path('confirmar/<int:pk>/', mostrar_confirmar_reserva, name='mostrar-confirmacion'),
    path('mis-reservas/<int:pk>/', mostrar_reservas, name='mis-reservas'),

    path('calendar/<int:pk>/', CalendarView.as_view(), name='calendar'),
    path('<int:event_id>/details/', reservas_details, name='reservas-details'),
]

"""
    path('detallecamping/<int:pk>/calendar/', views.CalendarView.as_view(), name='calendar'),
    path('<int:pk>/event/new/', views.create_event, name='event_new'),
    path('event/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:event_id>/details/', views.event_details, name='event-detail'),
    path('add_eventmember/<int:event_id>', views.add_eventmember, name='add_eventmember'),
    path('event/<int:pk>/remove', views.EventMemberDeleteView.as_view(), name="remove_event"),
    """

CampingsProject/reservas/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models

# Create your models here.

from sitio.models import Camping
from django.core.exceptions import ValidationError

class Reserva(models.Model):
	camping = models.ForeignKey(Camping, on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	fechaInicio=models.DateTimeField()
	fechaFin=models.DateTimeField()
	cantidadParcelas=models.PositiveIntegerField(default=0)
	confirmado = models.BooleanField(default=False)
	rechazado = models.BooleanField(default=False)
	noti_leida = models.BooleanField(default=False)

	def check_overlap(self, fixed_start, fixed_end, new_start, new_end):
		overlap = False
		if new_start == fixed_end or new_end == fixed_start:    #edge case
			overlap = False
		elif (new_start >= fixed_start and new_start <= fixed_end) or (new_end >= fixed_start and new_end <= fixed_end): #innner limits
			overlap = True
		elif new_start <= fixed_start and new_end >= fixed_end: #outter limits
			overlap = True

		return overlap

	def clean(self):
		if self.fechaFin <= self.fechaInicio:
			raise ValidationError('La fecha de fin no puede suceder antes que la de inicio.')

		# events = Reserva.objects.filter(confirmado=True)
		# if events.exists():
		# 	for event in events:
		# 		if self.check_overlap(event.fechaInicio, event.fechaFin, self.fechaInicio, self.fechaFin):
		# 			raise ValidationError(
		# 				'Hay una superposición con otra reserva: El día ' + str(event.fechaInicio.day) + ', ' + str(
		# 					event.fechaInicio) + '-' + str(event.fechaFin))

	def get_absolute_url(self):
		return reverse('/reservas/'+id+'/details/', args=(self.id,))

	@property
	def get_html_url(self):
		id = str(self.id)
		url = '/reservas/'+id+'/details/'
		return f'<a href="{url}"> Reserva hecha por {self.usuario} </a>'

CampingsProject/reservas/forms.py
from django import forms
from .models import Reserva
from django.forms.widgets import DateInput

class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = [
            'fechaInicio',
            'fechaFin',
            'cantidadParcelas',
        ]
        widgets = {
            'fechaInicio': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'fechaFin': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        labels = {
            'cantidadParcelas': 'Cantidad de Parcelas',
            'fechaInicio': 'Fecha de inicio de reserva',
            'fechaFin': 'Fecha de fin de reserva',
        }

    def __init__(self, *args, **kwargs):
        super(ReservaForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['fechaInicio'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['fechaFin'].input_formats = ('%Y-%m-%dT%H:%M',)

CampingsProject/reservas/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic
from django.utils.safestring import mark_safe

from datetime import datetime, date
from datetime import timedelta

from django.views.generic import ListView
from .models import Reserva
from .forms import ReservaForm
from .utils import Calendar
import calendar

from sitio.models import Camping
from django.contrib import messages

# Create your views here.
@login_required
def reservar(request, pk):
	next = request.POST.get('next', '/')
	pk_g = pk
	def get_object(self):
			return Reserva.objects.get(pk=self.request.GET.get('pk')) # or request.POST
	camping = Camping.objects.get(pk=pk)
	reservas = Reserva.objects.all()
	#dias_ya_reservados = False
	if request.POST:
		form = ReservaForm(data=request.POST)
		if form.is_valid():
			reserva = form.save(commit=False)
			#for r in reservas:
				#if (r.fechaInicio < reserva.fechaInicio or r.fechaFin > reserva.fechaFin) and (r.rechazado==False and r.confirmado==True):
					#dias_ya_reservados = True
			#if dias_ya_reservados:
			#	pass
				#form.add_error('fechaInicio', "Días ya reservados")
			#else:
			reserva.usuario = request.user
			reserva.camping =camping
			reserva.save()
			return HttpResponseRedirect(next)
	else:
		form = ReservaForm()
	return render(
		request,
		'reservar_calendario.html',
		{'form':form,
		'camping':camping,
		'reservas': reservas,
		'pk': camping.pk}
	)

@login_required
def mostrar_confirmar_reserva(request, pk):
	reserva= Reserva.objects.get(pk=pk)
	usuario = User.objects.get(pk=reserva.usuario.pk)
	return render(
		request,
		'confirmar_reserva.html',
		{
			'reserva': reserva,
			'usuario': usuario,
		}
	)


@login_required
def confirmar_reserva(request):
	if request.POST:
		pk = request.POST['pk']
		try:
			reserva = Reserva.objects.get(pk=pk)
			reserva.confirmado = True
			reserva.save()
			messages.success(request, 'Reserva confirmada con exito.')
			mensaje = 'Confirmado correctamente'
			HttpResponseRedirect('/')
		except Reserva.DoesNotExist:
			mensaje = 'Reserva no encontrada'
	else:
		mensaje= 'NO POST'

	return JsonResponse({
		'mensaje': mensaje,
		'url': '/',
	})

@login_required
def rechazar_reserva(request):
	if request.POST:
		pk = request.POST['pk']
		try:
			reserva = Reserva.objects.get(pk=pk)
			reserva.rechazado = True
			reserva.save()
			messages.success(request, 'Reserva rechazada.')
			mensaje = 'Rechazado correctamente'
			HttpResponseRedirect('/')
		except Reserva.DoesNotExist:
			mensaje = 'Reserva no encontrada'
	else:
		mensaje= 'NO POST'

	return JsonResponse({
		'mensaje': mensaje,
		'url': '/',
	})

def mostrar_reservas(request,pk):
	camping = Camping.objects.get(pk=pk)
	reservas = Reserva.objects.filter(camping=camping)

	return render(request, 'mostrar_reservas.html', {'reservas': reservas,})

def mis_reservas(request):
	reservas = []
	try:
		reservas = Reserva.objects.filter(usuario=request.user)
		for reserva in reservas:
			reserva.noti_leida = True
			reserva.save()
	except:
		pass

	return render(request, 'mis_reservas.html', {'reservas': reservas,})

@login_required()
def reservas_details(request, event_id):
	event = Reserva.objects.get(id=event_id)
	context = {
		'reserva': event,
	}
	return render(request, 'detalle_reservas.html', context)

class CalendarView(LoginRequiredMixin, ListView):
	template_name = 'calendar.html'

	def get_queryset(self, **kwargs):
		parametro = self.kwargs['pk']
		camping = Camping.objects.get(pk=parametro)
		reservas = Reserva.objects.all()
		for reserva in reservas:
			print(reserva.camping.nombre)
		print(parametro)
		print(camping.nombre)
		return Reserva.objects.filter(confirmado=True)

	def get_context_data(self, **kwargs):
		parametro = self.kwargs['pk']
		camping = Camping.objects.get(pk=parametro)
		nombre = camping.nombre

		context = super().get_context_data(**kwargs)
		d = get_date(self.request.GET.get('month', None))
		cal = Calendar(d.year, d.month)
		html_cal = cal.formatmonth(nombre, withyear=True)
		context['calendar'] = mark_safe(html_cal)
		context['prev_month'] = prev_month(d, nombre)
		context['next_month'] = next_month(d)
		context['pk'] = self.kwargs['pk']
		return context

def get_date(req_day):
	if req_day:
		year, month = (int(x) for x in req_day.split('-'))
		return date(year, month, day=1)
	return datetime.today()

def prev_month(d, nombre):
	first = d.replace(day=1)
	prev_month = first - timedelta(days=1)
	month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
	return month

def next_month(d):
	days_in_month = calendar.monthrange(d.year, d.month)[1]
	last = d.replace(day=days_in_month)
	next_month = last + timedelta(days=1)
	month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
	return month

CampingsProject/reservas/templates/calendar.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
    <title> Calendar </title>
</head>
<body>

    <div class="clearfix">
        <a class="btn btn-info left mr-2" href="/detallecamping/{{pk}}/"> Volver </a>
        <a class="btn btn-info right mr-2" href="{% url 'reservas:calendar' pk %}?{{ next_month }}"> Mes Siguiente >> </a>
        <a class="btn btn-info right mr-2" href="{% url 'reservas:calendar' pk %}?{{ prev_month }}"> << Mes Anterior </a>
        <a class="btn btn-info right mr-2" href="reservar/"> + Nueva Reserva </a>
    </div>
    <div style="color: green;">
        {{ calendar }}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

CampingsProject/reservas/templates/confirmar_reserva.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
    <br>
    <h5><ul>Confirmar reserva de {{reserva.usuario|upper}}</ul></h5>
    <br>
    <h6>Reserva de {{reserva.cantidadParcelas}} parcela/s desde {{reserva.fechaInicio}} hasta el {{reserva.fechaFin}}.</h6>
    <br>
    <h6><strong>Comunicate con {{reserva.usuario}} a través de {{usuario.email}}.</strong></h6>
    <br>
    <button class="btn btn-primary btn-md my-0 p confirmar" data-pk="{{ reserva.pk }}"">Confirmar reserva</button>
    </a>
    <button class="btn btn-danger btn-md my-0 p rechazar" data-pk="{{ reserva.pk }}">Rechazar reserva</button>
    </a>
    <br>
</div>
<br>
{% endblock content %}

{% block scripts_pie %}
<script type="text/javascript">
(function($) {
    'use strict';
    $('.confirmar').on('click', function() {
        var pk = $(this).data('pk');
        $.ajax({
            method: "POST",
            url: '/reservas/confirmar/',
            data: { pk: pk, csrfmiddlewaretoken: '{{ csrf_token }}' }
        })
        .done(function( datos ) {
            alert(datos.mensaje);
            window.location.href = datos.url;
        })
        .fail(function( jqXHR, textStatus ) {
            alert('Reserva confirmada!', 'Encontramos un problema: ' + jqXHR + ' estado: ' + textStatus, 'danger');
        });
    });
})(jQuery);

(function($) {
    'use strict';
    $('.rechazar').on('click', function() {
        var pk = $(this).data('pk');
        $.ajax({
            method: "POST",
            url: '/reservas/rechazar/',
            data: { pk: pk, csrfmiddlewaretoken: '{{ csrf_token }}' }
        })
        .done(function( datos ) {
            alert(datos.mensaje);
            window.location.href = datos.url;
        })
        .fail(function( jqXHR, textStatus ) {
            alert('Reserva rechazada!', 'Encontramos un problema: ' + jqXHR + ' estado: ' + textStatus, 'danger');
        });
    });
})(jQuery);
</script>
{% endblock %}

CampingsProject/reservas/templates/detalle_reservas.html
{% extends 'base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" type="button" onclick="history.back();" value="Back" name="button" class="btn"> Calendar </a>
        </div>
        <div class="clearfix">
            <h3>Reserva hecha por: {{ reserva.usuario }}</h3>
            <hr>
            <p>Desde la fecha <span style="color: gray;">{{ reserva.fechaInicio }}</span>
            <br> Hasta: <span style="color: gray;">{{ reserva.fechaFin }}</span></p>
            <hr>
            <p>Se reservaron {{ reserva.cantidadParcelas }} parcelas.</p>
        </div>
    </div>
{% endblock %}

CampingsProject/reservas/templates/mis_reservas.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="text-center">
    <br>
    <h5>Mis reservas</h5>
</div>
<br>
<div class="container text-center">
    <div class="row">
        <div class="col-sm-2"><strong>Fecha de inicio</strong></div>
        <div class="col-sm-2"><strong>Fecha de fin</strong></div>
        <div class="col-sm-2"><strong>Camping</strong></div>
        <div class="col-sm-2"><strong>Cantidad de parcelas</strong></div>
        <div class="col-sm-2"><strong>Estado de la reserva</strong></div>
    </div>
    <br>
    {% for reserva in reservas %}
    <div class="row">
        <p style="border: ridge #000000 2px;">
        <div class="col-sm-2">
            {{ reserva.fechaInicio }}
        </div>
        <div class="col-sm-2">
            {{ reserva.fechaFin }}
        </div>
        <div class="col-sm-2">
            {{ reserva.camping }}
        </div>
        <div class="col-sm-2">
            {{ reserva.cantidadParcelas }}
        </div>
        <div class="col-sm-2">
            {% if reserva.confirmado == True %}
                <p>Confirmada</p>
            {%else%}
                {% if reserva.rechazado == True %}
                    <p>Rechazada</p>
                {% endif %}
                {% if reserva.rechazado == False and reserva.confirmado == False %}
                    <p>Pendiente</p>
                {% endif %}
            {% endif %}
        </div>
    </p>
    </div>
    <br>
    {% endfor %}
</div>

{% endblock content %}

CampingsProject/reservas/templates/mostrar_reservas.html
{% extends "base.html" %}

{% block scripts_encabezado %}
<style>
    .btncerrar
    {
        width: 150px;
        height: 35px;
    }
</style>
{% endblock %}

{% block content %}
<div class="text-center">
    <br>
    <h5>Reservas de tu camping</h5>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-2"><strong>Usuario que reservo</strong></div>
        <div class="col-sm-2"><strong>Fecha de inicio</strong></div>
        <div class="col-sm-2"><strong>Fecha de fin</strong></div>
        <div class="col-sm-2"><strong>Cantidad de parcelas</strong></div>
        <div class="col-sm-2"><strong>Estado de la reserva</strong></div>
    </div>
    <br>
    {% for reserva in reservas %}
    <div class="row">
        <p style="border: ridge #000000 2px;">
        <div class="col-sm-2">
            {{ reserva.usuario }}
            {{ reserva.usuario.email }}
        </div>
        <div class="col-sm-2">
            {{ reserva.fechaInicio }}
        </div>
        <div class="col-sm-2">
            {{ reserva.fechaFin }}
        </div>
        <div class="col-sm-2">
            {{ reserva.cantidadParcelas }}
        </div>
        <div class="col-sm-2">
            {% if reserva.confirmado == True %}
                <p>Confirmada</p>
            {%else%}
                {% if reserva.rechazado == True %}
                    <p>Rechazada</p>
                {%else%}
                    <p>Click para confirmar o rechazar</p>
                        <br>
                        <br>
                        <a href="/reservas/confirmar/{{reserva.pk}}/" class="btn btn-secondary btncerrar">Ver</a>
                        <br>
                    <br>
                {% endif %}
            {% endif %}
        </div>
    </p>
    </div>
    <br>
    {% endfor %}
</div>
{% endblock content %}

CampingsProject/reservas/templates/reservar_calendario.html
{% extends "base.html" %}
{% load static %}
{% block scripts_encabezado %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/barra_lateral.css' %}">
{% endblock %}

{% block content %}
<div class="text-center">
    {% if form.errors %}
    <ul>
    <li><p>{{form.errors}}</p></li>
    </ul>
    {% endif %}

    <!-- <div class="text-center">
        {% for reserva in reservas %}
            <li>
                <p>Reserva de: {{reserva.usuario}}
                <br> Desde: {{reserva.fechaInicio}}
                <br> Hasta: {{reserva.fechaFin}}</p>
            </li>
        {% endfor %}
    </div> -->

    <div class="clearfix">
        <a class="btn btn-info left mr-2" href="/reservas/calendar/{{pk}}/"> Calendar </a>
    </div>
    <form action="{{ request.path }}" method="POST">{% csrf_token %}
        <div class="text-center">
            <table>
                <p>Fecha de inicio</p>
                {{form.fechaInicio}}
                <br>
                <p>Fecha fin</p>
                {{form.fechaFin}}
                <br>
                <p>Cantidad de parcelas</p>
                {{form.cantidadParcelas}}
                <br>
                <br>
                {# {{ form.as_table }} #}
            </table>
        </div>
        <input type="hidden" name="next" value="/reservas/calendar/{{pk}}/">
        <button type="submit" class="btn btn-primary">Realizar reserva</button>
        <a href="/reservas/calendar/{{pk}}/" class="btn btn-default">Cancelar</a>
        <br>
        <br>
    </form>
</div>

{% endblock content %}