CampingsProject/CampingsProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls), # url por defecto para administrar el sitio
    path('', include('sitio.urls')), # incluye las urls de la app pagina
    path('foro/', include('foro.urls')),
    path('reservas/', include('reservas.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'), #vista de contraseña cambiada correctamente
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CampingsProject/foro/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.forumposts, name='forumposts'),
    path('tema/<int:pk>/', views.forumpostdetail, name='forumpostdetail'),
    path('nuevotema/', views.addforumpost, name='addforumpost'),
    path('tema/<int:pk>/delete/', views.deleteforumpost, name='deleteforumpost'),
    path('respuesta/<int:pk>/delete/', views.deleteanswer, name='deleteanswer'),
    path('likeanswer/<int:pk>/', views.likeanswer, name= 'likeanswer'),
]

CampingsProject/sitio/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (home,
                    iniciar_sesion,
                    registrarse,
                    cerrar_sesion,
                    reservaciones,
                    detalle_camping,
                    campings,
                    listar,
                    agregar_editar,
                    eliminar_banner,
                    activate,
                    borrarcamping,
                    abmcamping,
                    eliminar_comentario,
                    autocomplete,
                    denuncias,
                    descartardenuncias,
                    autocompleteForumpost
                    )

from django.contrib.auth import views as auth_views
from django.conf.urls import url
from foro.views import forumpostdetail, deleteforumpost
from reservas.views import mis_reservas
from foro import views

app_name = 'sitio'
urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', iniciar_sesion, name='iniciosesion'),
    path('registrarse/', registrarse, name='registrarse'),
    path('cerrarsesion/', cerrar_sesion, name='cerrarsesion'),

    path('reservaciones/', reservaciones, name='reservaciones'),
    path('campings/<int:pk>/', campings, name = 'campings'),
    # path('campings/', campings, name='campings'),
    path('detallecamping/<int:pk>/', detalle_camping, name='detalle_camping'),
    path('banners/', listar, name='lista_banners'),
    path('banner/', agregar_editar, name='banner'),
    path('banner/<int:pk>/', agregar_editar, name='banner_detalle'),
    path('banner/<int:pk>/delete/', eliminar_banner, name='eliminar'),
    # path('nuevocamping/', nuevocamping, name='nuevocamping'),
    path('abmcamping/', abmcamping, name='abmcamping'),
    #path('modificarcamping/<int:pk>/', modificarcamping, name='modificarcamping'),
    path('borrarcamping/<int:pk>/', borrarcamping, name='borrarcamping'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    #comentarios
    path('comentario/<int:pk>/delete/', eliminar_comentario),
    path('reservas/', include('reservas.urls')),

    path('misreservas/', mis_reservas, name='misreservas'),

    path('search/', include('haystack.urls')),
    path('foro/search/', include('haystack.urls')),

    path('forumpostdetail/<int:pk>/', forumpostdetail, name='forumpostdetail'),
    path('deleteforumpost/<int:pk>/', deleteforumpost, name='deleteforumpost'),

    url(r'^search/autocomplete',autocomplete, name='autocomplete'),
    url(r'^foro/search/autocomplete',autocompleteForumpost, name='autocomplete'),

    path('denuncias/', denuncias, name='denuncias'),

    path('descartardenuncias/<int:pk>/', descartardenuncias, name= 'descartardenuncias'),

    path('denuncia/<int:pk>/', views.denuncia, name= 'denuncia'),
]

CampingsProject/templates/barra.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top py-3">
    {% block messages %}
        {% include "messages.html" %}
    {% endblock messages %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active"><a class="nav-link js-scroll-trigger" href="/"><big> Inicio </big><span class="sr-only">(current)</span></a></li>
        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/foro/"><big> Foro </big></a></li>
        {% if user.is_authenticated%}
            {% if camping == "" %}
                <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/" onClick="return confirm('Necesitas dar de alta tu camping para que los usuarios puedan reservar');"><big> Reservas de Tu camping </big></a></li>
            {% else %}
                {% if camping.usuarioAdmin == user %}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/reservas/mis-reservas/{{camping.pk}}/"><big> Reservas de Tu camping </big></a></li>
                {% endif %}
            {% endif %}
        {% endif %}
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons right">
        {% if request.user.is_authenticated %}
            <li class="nav-item dropdown"></li>
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i>
                    <big>{{ user.username }}</big>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item" href="/abmcamping/">Tu Camping</a>
                    {% if cant_mis_reservas > 0 %}
                    <a class="dropdown-item" href="/misreservas/">Mis reservas</a>
                    {% endif %}
                    {% if request.user.is_staff%}
                        <a class="dropdown-item" href="/denuncias/" id="btndenuncias">Denuncias</a>
                    {% endif %}
                    <a class="dropdown-item" href="/banners/">Configurar Banners</a>
                    <a class="dropdown-item" href="/cerrarsesion/">Cerrar sesion</a>
                </div>
            </li>
            {% include 'notificaciones.html' %}
        {% else %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i>
                    <big>Ingresar</big>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item text-dark" href="/accounts/login/">Iniciar sesion</a>
                    <a class="dropdown-item text-dark" href="/registrarse/">Registrarse</a>
                </div>
            </li>
        {% endif %}
    </ul>
</nav>

CampingsProject/templates/base.html
{% load static %}
{% load ratings%}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/star-ratings.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/starability-all.min.css' %}"/>

    {% block scripts_encabezado %}{% endblock %}

    <!-- <link href="{% static 'css/campings.css' %}" rel="stylesheet" type="text/css"> -->
</head>

<style>
    header.masthead {
        padding-top: 3rem;
        padding-bottom: calc(4rem - 4rem);
        background: #d4bd22;
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: scroll;
        background-size: cover;
        }
</style>

<body>

    <!--MENÚ, NAVBAR-->
    {% block barra %}
        {% include "barra.html" %}
    {% endblock barra %}
    {% block messages %}
    {% endblock messages %}

    <!-- Masthead-->
    <header class="masthead">
            <div class="row h-25 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <img src="{% static '/img/logo.png' %}" width="200" height="200">
                    <hr class="divider my-4" style="border-color: #d4bd22;"/>
                </div>
            </div>

        {% block header %}
        {% endblock %}
    </header>

    {% block content %}
    {% endblock content %}

    <footer>
        <div style="background-color: #079748; height: 3px;"></div>
        <div style="background-color: #ffffff; height: 3px;"></div>
        <div style="background-color: #d4bd22; height: 5px;"></div>
        <div style="background-color: #ffffff; height: 6px;" class="text-center">
            <p>Ramirez | Spahn | Llull</p>
        </div>
    </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/star-ratings.min.js' %}"></script>
    <script language="javascript" type="text/javascript"></script>

    {% block scripts_pie %} {% endblock %}

</body>

</html>

CampingsProject/templates/borrarcamping.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="text-center">
    <span title = "borrarcamping">Estás seguro de borrar el camping: {{ camping.nombre }}?</span>
</div>

<form  method="POST" class="post-form">
    {% csrf_token %}

    <a href="/">Cancelar</a>

    <input type="submit" name="confirm">
</form>

{% endblock content %}

CampingsProject/templates/comentarios_denunciados.html
{% extends "base.html" %}

{% block content %}
<br/>
<p><strong>Respuestas del foro denunciadas pendientes de revisión</strong></p>
{% if comentarios %}
<p>Las siguientes respuestas del foro han sido denunciadas 5 o más veces. Revise las mismas y tome una decisión al respecto.</p>
{% endif %}
{% for comment in comentarios %}

<div class="container"> 
    <div class="alert alert-warning" role="alert">                     
        <div class="date">
            <small>Fecha: {{ comment.fechaCreacion }}</small> 
            <br>
            Usuario denunciado: {{ comment.author }} 
            <br>
            Contenido publicado: {{ comment.contenido }}
            <br>
            Cantidad de denuncias: {{ comment.total_denuncias }}
            <a href="{% url 'deleteanswer' comment.pk %}"class="badge badge-danger"
                        onClick="return confirm('¿Seguro que quieres eliminar esta respuesta denunciada del foro?');">
                        <strong>Eliminar respuesta</strong>
            </a>
            <a href="{% url 'sitio:descartardenuncias' comment.pk %}"class="badge badge-success"
                        onClick="return confirm('¿Seguro que quieres descartar todas las denuncias hechas a esta respuesta del foro?');">
                        <strong>Descartar denuncias</strong>
            </a>
            <br>
            Motivo/s por los que fue denunciado:
            {% for motivo in motivos %}
                {% if motivo.0 == comment %}
                    {% for descripcion in motivo.1 %}
                        {{descripcion}} - 
                    {% endfor %}
                {% endif %}
            {% empty %}
                <p>No hay </p>
            {% endfor %}
        </div>
    </div>
</div>

{% empty %}
    <p>No hay respuestas denunciadas pendientes de revisión</p>
{% endfor %}

{% endblock content %}

CampingsProject/templates/detalle_camping.html
{% extends "base.html" %}

{% block content %}
<div class="text-center">
    <span title = "Bienvenidos"><h3><strong>{{camping.nombre}}</strong></h3>
    </span>
</div>
{% block star %}
{% endblock %}
{% include "banners/banner.html" %}
<br>

<div class="text-center">
<br>
<h5><ul>{{ camping.descripcion }}</ul></h5>
{% if user.is_authenticated %}
    <br>
    <!-- <a href="/reservas/{{ camping.pk }}/reservar/" class="btn btn-primary btn-md my-0 p">
        Reserva tu lugar!
        <br>
    </a> -->
    <a href="/reservas/calendar/{{ camping.pk }}/" class="btn btn-primary btn-md my-0 p">
        Reserva tu lugar!
        <br>
    </a>
{% endif %}
</div>
<br>
{% if camping.linkGoogleMaps != "" %}
    <div class="text-center">
        <iframe src="{{ camping.linkGoogleMaps }}"
            width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
        </iframe>
    </div>
{% endif %}
<br>
{% if servicios.count > 0 %}
<ul>
    <h3><strong>Servicios que ofrece:</strong></h3>
    <ul>
    {% for servicio in servicios %}
        <li>{{ servicio }}</li>
    {% endfor %}
    </ul>

</ul>
{% endif %}

<hr>

{% include "comentarios/comentarios.html" %}

{% endblock content %}

{% comment %}
<!-- {% block scripts_pie %}
<script>

(function($) {
    'use strict';
    $('.publicar').on('click', function() {
        var pk = $(this).data('pk');
        $.ajax({
            method: "POST",
            url: "{% url 'sitio:eliminar' %}",
            data: { pk: pk, csrfmiddlewaretoken: '{{ csrf_token }}' }
        })
        .done(function( datos ) {
            alert(datos.mensaje);
            location.reload();
        })
        .fail(function( jqXHR, textStatus ) {
            alert('Oops!!', 'Encontramos un problema: ' + jqXHR + ' estado: ' + textStatus, 'danger');
        });
    });
})(jQuery);
</script>

{% endblock %} -->

{% endcomment %}

CampingsProject/templates/home.html
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- Third party plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="{% static '/css/home.css' %}">
</head>

<style>
    header.masthead {
        padding-top: 10rem;
        padding-bottom: calc(10rem - 3rem);
        background: linear-gradient(to bottom, rgba(92, 77, 66, 0.8) 0%, rgba(92, 77, 66, 0.8) 100%), url('static/img/imagen.jpg');
        background-position: center;
        background-repeat: no-repeat;
        background-attachment: scroll;
        background-size: cover;
        }
</style>

<body>
    <!--MENÚ, NAVBAR-->
    {% comment %}
    <!-- <div class="container">
        <div class="col-md-12">
            <div class="row">
                {% block messages %}
                    {% include "messages.html" %}
                {% endblock messages %}
            </div>
            <div class="row">
                {% block barra %}
                    {% include "barra.html" %}
                {% endblock barra %}
            </div>
        </div>
    </div> -->
    {% endcomment %}
    {% block barra %}
        {% include "barra.html" %}
    {% endblock barra %}
    {% block messages %}
    {% endblock messages %}

    <!-- Masthead-->
    <header class="masthead">
        <div class="container h-auto">
            <div class="row h-10 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <img src="{% static '/img/logo.png' %}" width="200" height="200">
                    <hr class="divider my-4" style="border-color: #d4bd22;"/>
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 font-weight-light mb-5" style="color: white;">
                        Bienvenidos a una pagina dedicada a los amantes de acampar
                    </p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Buscar Campings!</a>
                </div>
            </div>
        </div>
    </header>

    <!-- About-->
    <section class="page-section bg-primary" id="about">
        <div class="container h-100">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <br>
                    <br>
                    {% include "search_bar.html" %}
                    <br>
                    <section id="zonas">
                        <div class="row row-cols-2">
                            {% for zona in zonas %}
                                <div class="list-group" style="padding: 1%; width: 30%;">
                                    <button style="background: #079748; border-color: #079748;" type="button" class="list-group-item list-group-item-action active" disabled>
                                    {{ zona.nombre }}
                                    </button>
                                    {% for localidad in localidades %}
                                        {% if localidad.zona == zona %}
                                        <button type="button" class="list-group-item list-group-item-action">
                                            <a style="color: #079748;" href="/campings/{{localidad.pk}}/">{{ localidad.nombre }}</a>
                                        </button>
                                        {% endif %}
                                    {% endfor %}
                                    <br>
                                </div>
                            {% endfor %}
                        </div>
                    </section>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </section>

    <br>
    <br>
    <br>

    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container h-50">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="mt-0">Comuniquese con nosotros!</h2>
                    <hr class="divider my-4" />
                    <p class="text-muted mb-5">El equipo de Vivis en carpa esta disponible para cualquier sugerencia o consulta. <br> No dude en llamar o contactarnos por email!</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                    <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                    <div>+1 (555) 123-4567</div>
                </div>
                <div class="col-lg-4 mr-auto text-center">
                    <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                    <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                    <a class="d-block" href="vivisencarpa@gmail.com">vivisencarpa@gmail.com</a>
                </div>
            </div>
        </div>
    </section>
    <br>
    <br>
    <br>
    <footer>
        <div style="background-color: #079748; height: 3px;"></div>
        <div style="background-color: #ffffff; height: 3px;"></div>
        <div style="background-color: #d4bd22; height: 5px;"></div>
        <div style="background-color: #ffffff; height: 6px;" class="text-center">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Vivis en Carpa</div></div>
            <p>Ramirez | Spahn | Llull</p>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>

</body>

</html>

CampingsProject/templates/home_copy.html
{% extends "detalle_camping.html" %}
{% load ratings %}


{% block star %}
<div class=text-center>
    {% ratings object %}
</div>
{% endblock %}

CampingsProject/templates/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}

CampingsProject/templates/mostrar_campings.html
{% extends "base.html" %}

{% block content %}
<style> 
    .card {
        background: -webkit-linear-gradient(to right, #ffffff, #dcf0e5);
        background:    -moz-linear-gradient(to right, #ffffff, #dcf0e5);
        background:         linear-gradient(to right, #ffffff, #dcf0e5);
    }
    .btn-outline-secondary {
        border-color: #079748;
    }
    .btn-outline-secondary:hover {
        background: #a8e0c1;
        border-color: #079748;
    }
</style>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for camping in campings %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm" style="background-color: #ffffff;">
                        {% if camping.foto_perfil %}
                        <img class="d-block w-100" src="{{ camping.foto_perfil.url }}" alt="First slide">
                        {% endif %}
                        <h3 style="text-align: center; color: #97075b;"><strong><em> {{ camping.nombre }} </em></strong></h3>
                        <div style="padding: 5px 20px; color: black;">
                            <p>{{ camping.descripcion }}</p>

                            <p><small> {{ camping.direccion }}, {{camping.localidad}} </small></p>

                            <p><small><a href={{camping.pagina}}>{{camping.pagina}}</a> <br> {{camping.telefono}} </small></p> 

                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">
                                        <a href="/detallecamping/{{camping.pk}}/" style="color: #079748;">Ver más...</a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

CampingsProject/templates/nuevocamping.html
{% extends "base.html" %}
{% block content %}

<br/>
<h2 class="text-center">TU CAMPING</h2>
<br/>

<div class="container">
    <div class="alert alert-success" role="alert">
        <div style="padding: 30px; width: 100%;" class="text-left">
            <form action="{{request.path}}" method="POST" enctype="multipart/form-data" >{% csrf_token %}
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Guardar</button>
            </form>
            {% if camping is not None%}
            <br>
            <a href="/borrarcamping/{{ camping.pk }}/" class="btn btn-danger" onClick="return confirm('¿Seguro que quieres borrar el camping {{ camping.nombre }}?');">
                Eliminar camping</a>
            {% endif %}
        </div>
    </div>
</div>
<br/>

{% endblock content %}

CampingsProject/templates/reservaciones.html
{% extends "base.html" %}

{% block content %}
<div class="text-center">
<span title = "Bienvenidos">Prueba para volver a la misma pagina
</span>
    <P>
        <a href="reservar" class="btn btn-primary btn-md my-0 p">
            RESERVAR
        </a>
    </P>
</div>

{% endblock content %}

CampingsProject/templates/search_bar.html
{% load static %}

<head>
    <link href="{% static 'css/search_bar.css' %}" rel="stylesheet" type="text/css" />
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="//jqueryui.com/jquery-wp-content/themes/jquery/js/plugins.js"></script>
    <script src="//jqueryui.com/jquery-wp-content/themes/jquery/js/main.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
</head>

<body>
    <form method="get" action="/search/" class="autocomplete-me">
        <div style="padding: 0px;">
            <div class="row">
                <div class="col-md-10" style="padding:0px">
                    <input type="text" class="form-control" id="id_q" name="q">
                </div>
                <div class="col-md-2" style="padding:0px">
                    <input class="btn btn-success" type="submit" value="Buscar!">
                </div>
            </div>
        </div>
    </form>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
    // In a perfect world, this would be its own library file that got included
    // on the page and only the ``$(document).ready(...)`` below would be present.
    // But this is an example.
    var Autocomplete = function(options) {
        this.form_selector = options.form_selector
        this.url = options.url || '/search/autocomplete/'
        this.delay = parseInt(options.delay || 300)
        this.minimum_length = parseInt(options.minimum_length || 3)
        this.form_elem = null
        this.query_box = null
    }

    Autocomplete.prototype.setup = function() {
        var self = this

        this.form_elem = $(this.form_selector)
        this.query_box = this.form_elem.find('input[name=q]')

        // Watch the input box.
        this.query_box.on('keyup', function() {
        var query = self.query_box.val()

        if(query.length < self.minimum_length) {
            return false
        }

        self.fetch(query)
        })

        // On selecting a result, populate the search field.
        this.form_elem.on('click', '.ac-result', function(ev) {
        self.query_box.val($(this).text())
        $('.ac-results').remove()
        return false
        })
    }

    Autocomplete.prototype.fetch = function(query) {
        var self = this

        $.ajax({
        url: this.url
        , data: {
            'q': query
        }
        , success: function(data) {
            self.show_results(data)
        }
        })
    }

    Autocomplete.prototype.show_results = function(data) {
        // Remove any existing results.
        $('.ac-results').remove()

        var results = data.results || []
        var results_wrapper = $('<div class="ac-results" style="cursor: pointer;background-color: #fff;padding: 2 solid #d4d4d4;border-radius: 5px;text-align: left;padding-left: 10;"></div>')
        var base_elem = $('<div class="result-wrapper"><a href="#" style="color:black" class="ac-result"></a></div>')

        if(results.length > 0) {
        for(var res_offset in results) {
            var elem = base_elem.clone()
            // Don't use .html(...) here, as you open yourself to XSS.
            // Really, you should use some form of templating.
            elem.find('.ac-result').text(results[res_offset])
            results_wrapper.append(elem)
        }
        }
        else {
        var elem = base_elem.clone()
        elem.text("No existe un resultado con ese nombre.")
        results_wrapper.append(elem)
        }

        this.query_box.after(results_wrapper)
    }

    $(document).ready(function() {
        window.autocomplete = new Autocomplete({
        form_selector: '.autocomplete-me'
        })
        window.autocomplete.setup()
    })
</script>

</body>